name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master   # o la rama que uses para tu código

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0 

      - name: Install dependencies
        run: npm install

      - name: Build web
        run: flutter build web --release --base-href /duo/

      - name: Copy to docs/
        run: |
          rm -rf docs
          mkdir docs
          cp -r build/web/* docs/

      - name: Commit and push to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages